import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { ResumeAnalysisResult } from '../services/resumeService';

export async function generateAnalysisPDF(result: ResumeAnalysisResult): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentW = pageW - margin * 2;

  const purple: [number, number, number] = [37, 99, 235]; // Primary blue in CareerLens instead of raw purple
  const purpleLight: [number, number, number] = [239, 246, 255]; // Blue-50
  const green: [number, number, number] = [34, 197, 94];
  const greenLight: [number, number, number] = [240, 253, 244];
  const red: [number, number, number] = [239, 68, 68];
  const redLight: [number, number, number] = [254, 242, 242];
  const gray800: [number, number, number] = [17, 24, 39];
  const gray500: [number, number, number] = [107, 114, 128];
  const gray100: [number, number, number] = [243, 244, 246];
  const white: [number, number, number] = [255, 255, 255];
  const amber: [number, number, number] = [245, 158, 11];

  const scoreRGB = (s: number): [number, number, number] => (s >= 75 ? green : s >= 50 ? amber : red);
  const docEx = doc as any;

  const addFooter = (pageNum: number, total: number) => {
    doc.setFontSize(8);
    doc.setTextColor(gray500[0], gray500[1], gray500[2]);
    doc.text('Generated by CareerLens CV Intelligence', margin, pageH - 10);
    doc.text(`Page ${pageNum} of ${total}`, pageW - margin, pageH - 10, { align: 'right' });
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, pageH - 14, pageW - margin, pageH - 14);
  };

  // Header background banner
  doc.setFillColor(purple[0], purple[1], purple[2]);
  doc.rect(0, 0, pageW, 44, 'F');
  doc.setFontSize(22);
  doc.setTextColor(white[0], white[1], white[2]);
  doc.setFont('helvetica', 'bold');
  doc.text('CareerLens Analysis Report', margin, 20);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(210, 225, 255);
  doc.text(
    `Generated ${new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' })}`,
    margin,
    29
  );
  doc.text(`Target Role Context: ${result.jd_title}`, margin, 37);

  // Score Badge
  const scoreRGBVal = scoreRGB(result.match_score);
  doc.setFillColor(scoreRGBVal[0], scoreRGBVal[1], scoreRGBVal[2]);
  doc.roundedRect(pageW - margin - 28, 8, 28, 28, 3, 3, 'F');
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(white[0], white[1], white[2]);
  doc.text(`${result.match_score}`, pageW - margin - 14, 22, { align: 'center' });
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text('/100  Match', pageW - margin - 14, 29, { align: 'center' });

  let y = 56;
  const halfW = (contentW - 6) / 2;

  // Match Score metrics layout
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(gray800[0], gray800[1], gray800[2]);
  doc.text('Overall Match Score', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  const matchColor = scoreRGB(result.match_score);
  doc.setTextColor(matchColor[0], matchColor[1], matchColor[2]);
  doc.text(`${result.match_score}/100`, margin + halfW, y, { align: 'right' });
  y += 4;
  doc.setFillColor(gray100[0], gray100[1], gray100[2]);
  doc.roundedRect(margin, y, halfW, 5, 1, 1, 'F');
  doc.setFillColor(matchColor[0], matchColor[1], matchColor[2]);
  doc.roundedRect(margin, y, (halfW * result.match_score) / 100, 5, 1, 1, 'F');

  const col2x = margin + halfW + 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(gray800[0], gray800[1], gray800[2]);
  doc.text('ATS Score', col2x, y - 4);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  const atsColor = scoreRGB(result.ats_score);
  doc.setTextColor(atsColor[0], atsColor[1], atsColor[2]);
  doc.text(`${result.ats_score}/100`, col2x + halfW, y - 4, { align: 'right' });
  doc.setFillColor(gray100[0], gray100[1], gray100[2]);
  doc.roundedRect(col2x, y, halfW, 5, 1, 1, 'F');
  doc.setFillColor(atsColor[0], atsColor[1], atsColor[2]);
  doc.roundedRect(col2x, y, (halfW * result.ats_score) / 100, 5, 1, 1, 'F');
  y += 14;

  // Summary box
  doc.setFillColor(purpleLight[0], purpleLight[1], purpleLight[2]);
  const summaryLines = doc.splitTextToSize(result.summary, contentW - 8);
  const summaryH = summaryLines.length * 5.5 + 12;
  doc.roundedRect(margin, y, contentW, summaryH, 3, 3, 'F');
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(purple[0], purple[1], purple[2]);
  doc.text('SUMMARY', margin + 4, y + 7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(30, 41, 59);
  doc.text(summaryLines, margin + 4, y + 13);
  y += summaryH + 8;

  // Strong points table
  autoTable(doc, {
    startY: y,
    head: [['#', 'Strong Point']],
    body: result.strong_points.map((p, i) => [`${i + 1}`, p]),
    margin: { left: margin, right: margin },
    styles: { fontSize: 8.5, cellPadding: 3, textColor: gray800, overflow: 'linebreak' },
    headStyles: { fillColor: green, textColor: white, fontStyle: 'bold', fontSize: 9 },
    alternateRowStyles: { fillColor: greenLight },
    columnStyles: { 0: { cellWidth: 9, halign: 'center', fontStyle: 'bold' } }
  });
  y = docEx.lastAutoTable.finalY + 8;

  if (y > pageH - 80) {
    doc.addPage();
    y = 20;
  }

  // Weak points table
  autoTable(doc, {
    startY: y,
    head: [['#', 'Area for Improvement']],
    body: result.weak_points.map((p, i) => [`${i + 1}`, p]),
    margin: { left: margin, right: margin },
    styles: { fontSize: 8.5, cellPadding: 3, textColor: gray800, overflow: 'linebreak' },
    headStyles: { fillColor: red, textColor: white, fontStyle: 'bold', fontSize: 9 },
    alternateRowStyles: { fillColor: redLight },
    columnStyles: { 0: { cellWidth: 9, halign: 'center', fontStyle: 'bold' } }
  });
  y = docEx.lastAutoTable.finalY + 8;

  // ATS Tips
  if (result.ats_tips && result.ats_tips.length > 0) {
    if (y > pageH - 70) {
      doc.addPage();
      y = 20;
    }
    autoTable(doc, {
      startY: y,
      head: [['ATS Improvement Tips']],
      body: result.ats_tips.map((t) => [t]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 8.5, cellPadding: 3, textColor: gray800, overflow: 'linebreak' },
      headStyles: { fillColor: [245, 158, 11], textColor: white, fontStyle: 'bold', fontSize: 9 },
      alternateRowStyles: { fillColor: [255, 251, 235] }
    });
    y = docEx.lastAutoTable.finalY + 8;
  }

  // Per-JD scores
  if (result.per_jd_scores && result.per_jd_scores.length > 0) {
    if (y > pageH - 70) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(gray800[0], gray800[1], gray800[2]);
    doc.text('Per-JD Score Breakdown', margin, y);
    y += 6;
    autoTable(doc, {
      startY: y,
      head: [['Role', 'Company', 'Score', 'Key Match', 'Key Gap']],
      body: result.per_jd_scores.map((s) => [s.title, s.company, `${s.score}/100`, s.key_match, s.key_gap]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 8, cellPadding: 3, textColor: gray800, overflow: 'linebreak' },
      headStyles: { fillColor: purple, textColor: white, fontStyle: 'bold', fontSize: 8.5 },
      alternateRowStyles: { fillColor: purpleLight },
      columnStyles: { 0: { cellWidth: 35 }, 1: { cellWidth: 28 }, 2: { cellWidth: 18, halign: 'center', fontStyle: 'bold' } },
      didParseCell: (data) => {
        if (data.column.index === 2 && data.section === 'body') {
          const score = parseInt(String(data.cell.raw));
          const scoreColor = scoreRGB(score);
          data.cell.styles.textColor = scoreColor;
        }
      }
    });
    y = docEx.lastAutoTable.finalY + 8;
  }

  // Keywords
  if (result.keywords && result.keywords.length > 0) {
    if (y > pageH - 70) {
      doc.addPage();
      y = 20;
    }
    const present = result.keywords.filter((k) => k.in_cv).map((k) => k.word);
    const missing = result.keywords.filter((k) => !k.in_cv).map((k) => k.word);
    autoTable(doc, {
      startY: y,
      head: [['✓ Present in CV', '✗ Missing from CV']],
      body: [[present.join(', ') || '—', missing.join(', ') || '—']],
      margin: { left: margin, right: margin },
      styles: { fontSize: 8.5, cellPadding: 4, textColor: gray800, overflow: 'linebreak' },
      headStyles: { fillColor: [55, 65, 81], textColor: white, fontStyle: 'bold', fontSize: 9 },
      didParseCell: (data) => {
        if (data.section === 'body') {
          data.cell.styles.textColor = data.column.index === 0 ? [22, 163, 74] : [220, 38, 38];
        }
      }
    });
  }

  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    addFooter(p, totalPages);
  }

  doc.save(`careerlens-cv-analysis-${Date.now()}.pdf`);
}
